enableAES: false
replicaCount: 1
service:
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
    - name: mqtt-adapter
      port: 1883
      targetPort: 1883
    - name: mqtt-adaptersec
      port: 8883
      targetPort: 8883
    - name: device-registry
      port: 28080
      targetPort: 28080
    - name: dispatch-router
      port: 5671
      targetPort: 15671
    - name: grafana
      port: 3000
      targetPort: 3000
    - name: jaeger
      port: 16686
      targetPort: 16686
    - name: prometheus
      port: 9090
      targetPort: 9090
    - name: kafka
      port: 9092
      targetPort: 9092
    - name: mongodb
      port: 27017
      targetPort: 27017
    - name: mongo-telemetry
      port: 28018
      targetPort: 28018
