volumePermissions:
  enabled: true
livenessProbe:
  initialDelaySeconds: 700
readinessProbe:
  initialDelaySeconds: 20
logsDirs: /bitnami/kafka/data1
persistence:
  existingClaim: "kafkapvc"
  size: 5Gi
zookeeper:
  persistence:
    existingClaim: "zookeeperpvc"
    size: 5Gi
  auth:
    enabled: true
    clientUser: zookeeperUser
    clientPassword: zookeeperPassword
    serverUsers: zookeeperUser
    serverPasswords: zookeeperPassword
externalAccess:
  enabled: true
  service:
    type: LoadBalancer
    port: 9092
    nodePorts:
      - 32092
  autoDiscovery:
    enabled: true
serviceAccount:
  create: true
rbac:
  create: true
nameOverride: kafka
service:
  port: 9094
auth:
  clientProtocol: sasl
  interBrokerProtocol: sasl
  sasl:
    mechanism: plain
    jaas:
      clientUsers:
        - "hono"
        - "connect"
      clientPasswords:
        - "hono-secret"
        - "connect"
      zookeeperUser: zookeeperUser
      zookeeperPassword: zookeeperPassword
extraDeploy: |-
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: {{ include "kafka.fullname" . }}-connect
      labels: {{- include "kafka.labels" . | nindent 6 }}
        app.kubernetes.io/component: connector
    spec:
      replicas: 1
      selector:
        matchLabels: {{- include "kafka.matchLabels" . | nindent 8 }}
          app.kubernetes.io/component: connector
      template:
        metadata:
          labels: {{- include "kafka.labels" . | nindent 10 }}
            app.kubernetes.io/component: connector
        spec:
          containers:
            - name: connect
              image: ghcr.io/smaddis/kafka-connect-mongo:1.6.1
              imagePullPolicy: IfNotPresent
              command:
                - /bin/bash
                - -ec
                - |
                  /opt/bitnami/kafka/bin/connect-standalone.sh /config/connect-standalone.properties /config/mongodb.properties
              ports:
                - name: connector
                  containerPort: 8083
              volumeMounts:
                - name: configuration
                  mountPath: /config
          volumes:
            - name: configuration
              configMap:
                name: {{ include "kafka.fullname" . }}-connect
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: {{ include "kafka.fullname" . }}-connect
      labels: {{- include "kafka.labels" . | nindent 6 }}
        app.kubernetes.io/component: connector
    data:
      connect-standalone.properties: |-
        bootstrap.servers = {{ include "kafka.fullname" . }}-0.{{ include "kafka.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:{{ .Values.service.port }}
        key.converter=org.apache.kafka.connect.json.JsonConverter
        value.converter=org.apache.kafka.connect.json.JsonConverter
        key.converter.schemas.enable=true
        value.converter.schemas.enable=true
        offset.storage.file.filename=/tmp/connect.offsets
        offset.flush.interval.ms=10000
        plugin.path=/opt/bitnami/kafka/plugins
        sasl.mechanism=PLAIN
        security.protocol=SASL_PLAINTEXT
        sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
          username="connect" \
          password="conect";
        consumer.sasl.mechanism=PLAIN
        consumer.security.protocol=SASL_PLAINTEXT
        consumer.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
          username="connect" \
          password="conect";
      mongodb.properties: |-
        connection.uri=mongodb://honouser:hono-secret@mongodb.default.svc.cluster.local:27017/mydb
        name=mongo-sink
        topics=mytopic
        connector.class=com.mongodb.kafka.connect.MongoSinkConnector
        tasks.max=1
        key.converter=org.apache.kafka.connect.json.JsonConverter
        value.converter=org.apache.kafka.connect.json.JsonConverter
        key.converter.schemas.enable=false
        value.converter.schemas.enable=false
        database=mydb
        collection=sink
  - apiVersion: v1
    kind: Service
    metadata:
      name: {{ include "kafka.fullname" . }}-connect
      labels: {{- include "kafka.labels" . | nindent 6 }}
        app.kubernetes.io/component: connector
    spec:
      ports:
        - protocol: TCP
          port: 8083
          targetPort: connector
      selector: {{- include "kafka.matchLabels" . | nindent 6 }}
        app.kubernetes.io/component: connector




        listeners: 
  - INTERNAL://localhost:9093
  - CLIENT://kafka-0.kafka-headless.default.svc.cluster.local:9094
  - EXTERNAL://kafka-0.kafka-headless.default.svc.cluster.local:29092
advertisedListeners: 
  - INTERNAL://localhost:9093
  - CLIENT://kafka-0.kafka-headless.default.svc.cluster.local:9094
  - EXTERNAL://20.82.43.249:9092
interBrokerListenerName: EXTERNAL