{
 "title": "Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Telemetry</span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Events</span>\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Commands</span>\n</div>"
  },
  {
   "title": "messages",
   "type": "graph",
   "description": "average rate of telemetry messages received from devices",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "none", "label": "messages/sec" }
   ],
   "targets": [
    {
     "expr": "sum(irate(hono_messages_received_seconds_count{type=\"telemetry\",status=\"unprocessable\"}[$__range]))",
     "legendFormat": "unprocessable"
    },
    {
     "expr": "sum(irate(hono_messages_received_seconds_count{type=\"telemetry\",status=\"undeliverable\"}[$__range]))",
     "legendFormat": "undeliverable"
    },
    {
     "expr": "sum(irate(hono_messages_received_seconds_count{type=\"telemetry\",status=\"forwarded\"}[$__range]))",
     "legendFormat": "forwarded"
    }
   ]
  },
  {
   "title": "messages",
   "type": "graph",
   "description": "average rate of events received from devices",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "none", "label": "messages/sec" }
   ],
   "targets": [
    {
     "expr": "sum(irate(hono_messages_received_seconds_count{type=\"event\",status=\"unprocessable\"}[$__range]))",
     "legendFormat": "unprocessable"
    },
    {
     "expr": "sum(irate(hono_messages_received_seconds_count{type=\"event\",status=\"undeliverable\"}[$__range]))",
     "legendFormat": "undeliverable"
    },
    {
     "expr": "sum(irate(hono_messages_received_seconds_count{type=\"event\",status=\"forwarded\"}[$__range]))",
     "legendFormat": "forwarded"
    }
   ]
  },
  {
   "title": "messages",
   "type": "graph",
   "description": "average rate of commands sent to devices",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "none", "label": "messages/sec" }
   ],
   "targets": [
    {
     "expr": "sum(irate(hono_commands_received_seconds_count{direction=~\"one-way|request\",status=\"unprocessable\"}[$__range]))",
     "legendFormat": "unprocessable"
    },
    {
     "expr": "sum(irate(hono_commands_received_seconds_count{direction=~\"one-way|request\",status=\"undeliverable\"}[$__range]))",
     "legendFormat": "undeliverable"
    },
    {
     "expr": "sum(irate(hono_commands_received_seconds_count{direction=~\"one-way|request\",status=\"forwarded\"}[$__range]))",
     "legendFormat": "forwarded"
    }
   ]
  },
  {
   "title": "payload",
   "type": "graph",
   "description": "average rate of data received from devices as payload of telemetry messages",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "bytes/sec" }
   ],
   "targets": [
    {
     "expr": "sum(irate(hono_messages_payload_bytes_sum{type=\"telemetry\",status=\"unprocessable\"}[$__range]))",
     "legendFormat": "unprocessable"
    },
    {
     "expr": "sum(irate(hono_messages_payload_bytes_sum{type=\"telemetry\",status=\"undeliverable\"}[$__range]))",
     "legendFormat": "undeliverable"
    },
    {
     "expr": "sum(irate(hono_messages_payload_bytes_sum{type=\"telemetry\",status=\"forwarded\"}[$__range]))",
     "legendFormat": "forwarded"
    }
   ]
  },
  {
   "title": "payload",
   "type": "graph",
   "description": "average rate of data received from devices as payload of events",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "bytes/sec" }
   ],
   "targets": [
    {
     "expr": "sum(irate(hono_messages_payload_bytes_sum{type=\"event\",status=\"unprocessable\"}[$__range]))",
     "legendFormat": "unprocessable"
    },
    {
     "expr": "sum(irate(hono_messages_payload_bytes_sum{type=\"event\",status=\"undeliverable\"}[$__range]))",
     "legendFormat": "undeliverable"
    },
    {
     "expr": "sum(irate(hono_messages_payload_bytes_sum{type=\"event\",status=\"forwarded\"}[$__range]))",
     "legendFormat": "forwarded"
    }
   ]
  },
  {
   "title": "payload",
   "type": "graph",
   "description": "average rate of data sent to devices as payload of commands",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "bytes/sec" }
   ],
   "targets": [
    {
     "expr": "sum(irate(hono_commands_payload_bytes_sum{direction=~\"one-way|request\",status=\"unprocessable\"}[$__range]))",
     "legendFormat": "unprocessable"
    },
    {
     "expr": "sum(irate(hono_commands_payload_bytes_sum{direction=~\"one-way|request\",status=\"undeliverable\"}[$__range]))",
     "legendFormat": "undeliverable"
    },
    {
     "expr": "sum(irate(hono_commands_payload_bytes_sum{direction=~\"one-way|request\",status=\"forwarded\"}[$__range]))",
     "legendFormat": "forwarded"
    }
   ]
  },
  {
   "title": "undeliverable rate",
   "type": "graph",
   "description": "average rate of valid telemetry messages received from devices which could not be delivered downstream",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none", "label": "percent" }
   ],
   "targets": [
    {
     "expr": "(100 * sum(irate(hono_messages_received_seconds_count{type=\"telemetry\",qos=\"0\",status=\"undeliverable\"}[$__range])))\n/\nsum(irate(hono_messages_received_seconds_count{type=\"telemetry\",qos=\"0\"}[$__range]))",
     "legendFormat": "QoS 0"
    },
    {
     "expr": "(100 * sum(irate(hono_messages_received_seconds_count{type=\"telemetry\",qos=\"1\",status=\"undeliverable\"}[$__range])))\n/\nsum(irate(hono_messages_received_seconds_count{type=\"telemetry\",qos=\"1\"}[$__range]))",
     "legendFormat": "QoS 1"
    }
   ]
  },
  {
   "title": "undeliverable rate",
   "type": "graph",
   "description": "average rate of valid events received from devices which could not be delivered downstream",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "none", "label": "percent" }
   ],
   "targets": [
    {
     "expr": "(100 * sum(irate(hono_messages_received_seconds_count{type=\"event\",status=\"undeliverable\"}[$__range])))\n/\nsum(irate(hono_messages_received_seconds_count{type=\"event\"}[$__range]))",
     "legendFormat": "not forwarded"
    }
   ]
  },
  {
   "title": "undeliverable rate",
   "type": "graph",
   "description": "average rate of valid commands received from applications which could not be delivered to devices",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "none", "label": "percent" }
   ],
   "targets": [
    {
     "expr": "(100 * sum(irate(hono_commands_received_seconds_count{direction=~\"one-way|request\",status=\"undeliverable\"}[$__range])))\n/\nsum(irate(hono_commands_received_seconds_count{direction=\"one-way|request\"}[$__range]))",
     "legendFormat": "not forwarded"
    }
   ]
  },
  {
   "title": "Service Instances",
   "type": "table",
   "description": "The number of containers running for each service.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 26 },
   "targets": [
    { "expr": "sum(up) by (job)" }
   ]
  }
 ]
}