{
 "title": "Message details",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "componentname",
    "label": "Adapter",
    "query": "label_values(hono_messages_received_seconds_count,component_name)"
   },
   { "name": "tenant", "label": "Tenant", "query": ".+" },
   {
    "name": "type",
    "label": "Type",
    "query": "label_values(hono_messages_received_seconds_count,type)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(hono_messages_received_seconds_count,host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Succeeded",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(hono_messages_received_seconds_count{status=\"forwarded\",component_name=~\"$componentname\",type=~\"$type\",tenant=~\"$tenant\",host=~\"$instance\"}[$__range]))",
     "legendFormat": "forwarded"
    }
   ]
  },
  {
   "title": "avg",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(hono_messages_received_seconds_count{status=\"forwarded\",component_name=~\"$componentname\",type=~\"$type\",tenant=~\"$tenant\",host=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "avg",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(hono_messages_received_seconds_count{status=\"forwarded\",component_name=~\"$componentname\",type=~\"$type\",tenant=~\"$tenant\",host=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "avg",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(hono_messages_received_seconds_count{status=\"forwarded\",component_name=~\"$componentname\",type=~\"$type\",tenant=~\"$tenant\",host=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Payload",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(hono_messages_payload_bytes_sum{component_name=~\"$componentname\",type=~\"$type\",status=\"forwarded\",tenant=~\"$tenant\",host=~\"$instance\"}[$__range]))",
     "legendFormat": "forwarded"
    },
    {
     "expr": "sum(irate(hono_messages_payload_bytes_sum{component_name=~\"$componentname\",type=~\"$type\",status=\"undeliverable\",tenant=~\"$tenant\",host=~\"$instance\"}[$__range]))",
     "legendFormat": "undeliverable"
    },
    {
     "expr": "sum(irate(hono_messages_payload_bytes_sum{component_name=~\"$componentname\",type=~\"$type\",status=\"unprocessable\",tenant=~\"$tenant\",host=~\"$instance\"}[$__range]))",
     "legendFormat": "unprocessable"
    }
   ]
  },
  {
   "title": "avg",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 6 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(hono_messages_payload_bytes_sum{component_name=~\"$componentname\",type=~\"$type\",tenant=~\"$tenant\",host=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "avg",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 8 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(hono_messages_payload_bytes_sum{component_name=~\"$componentname\",type=~\"$type\",tenant=~\"$tenant\",host=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "avg",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 10 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(hono_messages_payload_bytes_sum{component_name=~\"$componentname\",type=~\"$type\",tenant=~\"$tenant\",host=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(hono_messages_received_seconds_count{component_name=~\"$componentname\",type=~\"$type\",status=\"undeliverable\",tenant=~\"$tenant\",host=~\"$instance\"}[$__range]))",
     "legendFormat": "undeliverable"
    },
    {
     "expr": "sum(irate(hono_messages_received_seconds_count{component_name=~\"$componentname\",type=~\"$type\",status=\"unprocessable\",tenant=~\"$tenant\",host=~\"$instance\"}[$__range]))",
     "legendFormat": "unprocessable"
    }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(rate(hono_messages_received_seconds_count{component_name=~\"$componentname\",type=~\"$type\",status!=\"forwarded\",tenant=~\"$tenant\",host=~\"$instance\"}[$__interval]))\n/\n sum(rate(hono_messages_received_seconds_count{component_name=~\"$componentname\",type=~\"$type\",tenant=~\"$tenant\",host=~\"$instance\"}[$__interval])))\n* 100\n"
    }
   ]
  }
 ]
}