architecture: "standalone"
persistence:
  enabled: true
  existingClaim: "mongopvc"
  mountPath: /bitnami/mongodb
  subPath: device-reg
  accessModes: "ReadWriteMany"
#useStatefulSet: true
metrics:
  enabled: true
auth:
  database: "honodb"
volumePermissions:
  enabled: true
service:
  nameOverride: "mongodb-devicereg"
  port: 27017

#architecture: "standalone"
#useStatefulSet: true
#auth: 
#  enabled: true
#  database: "honodb"
#persistence:
#  enabled: true
#  existingClaim: "mongopvc"
#  storageClass: "azure-disk-retain"
#  accessModes: "ReadWriteMany"
#metrics:
#  enabled: true

# Uncomment these if you want the DB to be externally available. NB! Remember that this 
# script also has auth credentials, so use external access with caution.
# 
# externalAccess:
#   enabled: true
# service:
#   type: "LoadBalancer"