prometheus:
  createInstance: false
jaegerBackendExample:
  enabled: false
jaegerAgentConf:
  REPORTER_GRPC_HOST_PORT: "jaeger-operator-jaeger-collector:14250"
grafana:
  enabled: false
mongodb:
  createInstance: false
deviceRegistryExample:
  type: "mongodb"
  addExampleData: false
  mongoDBBasedDeviceRegistry:
    mongodb:
      host: "mongodb"
      port: 27017
      dbName: "honodb"
adapters:
  http:
    enabled: false
messagingNetworkTypes:
  - kafka
