#architecture cannot be "high-availability" unless kubernetes persistent volume claim access mode is "ReadWriteMany"
architecture: "high-availability"
database: "monitoring_data"
adminUser:
  name: "root"
  pwd: "root"
user:
  name: "username"
  pwd: "password"
readUser:
  name: "readuser"
  pwd: "password"
writeUser:
  name: "writeuser"
  pwd: "password"


metrics:
  enabled: true
  service:
    type: "ClusterIP"
    port: 9122

influxdb:
  replicaCount: 2
  service:
    type: "LoadBalancer"
    port: 8086
  configuration: |-
    reporting-disabled = true

persistence:
  enabled: true
  existingClaim: "influxpvc"
