#architecture cannot be "high-availability" unless kubernetes persistent volume claim access mode is "ReadWriteMany"
architecture: "standalone"
database: "monitoring_data"
adminUser:
  name: "root"
  pwd: "root"
user:
  name: "username"
  pwd: "password"
readUser:
  name: "readuser"
  pwd: "password"
writeUser:
  name: "writeuser"
  pwd: "password"


metrics:
  enabled: true
  service:
    type: "ClusterIP"
    port: 9122

influxdb:
  #Only replicaCount 1 is supported with standalone architecture
  replicaCount: 1
  service:
    type: "LoadBalancer"
    port: 8086
#  existingConfiguration: name of config map object
  configuration: |-
    reporting-disabled = true
#    bind-address = "127.0.0.1:8086"

persistence:
  enabled: true
  existingClaim: "influx-pvc"
